Repository square/workflow, pull requests merged in 2019-12, with the labels that each got.

#790 Add variance to StatelessWorkflow type parameters.
  kotlin/workflow-core/src/main/java/com/squareup/workflow/StatelessWorkflow.kt
Labels: blocked

#802 Add a benchmark that just alternates a single leaf.
  kotlin/workflow-runtime/src/jmh/java/com/squareup/workflow/WorkflowNodeBenchmark.kt
Labels: enhancement

#817 BREAKING: WorkflowAction.Mutator deprecated by .Updater (#812, #813)
  kotlin/samples/containers/app-poetry/src/main/java/com/squareup/sample/poetryapp/PoemListWorkflow.kt
  kotlin/samples/containers/app-poetry/src/main/java/com/squareup/sample/poetryapp/PoemsBrowserWorkflow.kt
  kotlin/samples/containers/poetry/src/main/java/com/squareup/sample/poetry/PoemWorkflow.kt
  kotlin/samples/containers/poetry/src/main/java/com/squareup/sample/poetry/StanzaListWorkflow.kt
  kotlin/samples/containers/poetry/src/main/java/com/squareup/sample/poetry/StanzaWorkflow.kt
  kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/DungeonAppWorkflow.kt
  kotlin/samples/dungeon/common/src/main/java/com/squareup/sample/dungeon/AiWorkflow.kt
  kotlin/samples/dungeon/common/src/main/java/com/squareup/sample/dungeon/GameWorkflow.kt
  kotlin/samples/dungeon/common/src/main/java/com/squareup/sample/dungeon/PlayerWorkflow.kt
  kotlin/samples/dungeon/timemachine-shakeable/src/main/java/com/squareup/sample/timemachine/shakeable/ShakeableTimeMachineWorkflow.kt
  kotlin/samples/dungeon/timemachine/src/main/java/com/squareup/sample/timemachine/TimeMachineWorkflow.kt
  kotlin/samples/dungeon/timemachine/src/test/java/com/squareup/sample/timemachine/TimeMachineWorkflowTest.kt
  kotlin/samples/hello-terminal/hello-terminal-app/src/main/java/com/squareup/sample/helloterminal/BlinkingCursorWorkflow.kt
  kotlin/samples/hello-terminal/hello-terminal-app/src/main/java/com/squareup/sample/helloterminal/HelloTerminalWorkflow.kt
  kotlin/samples/hello-terminal/todo-terminal-app/src/main/java/com/squareup/sample/hellotodo/EditTextWorkflow.kt
  kotlin/samples/hello-terminal/todo-terminal-app/src/main/java/com/squareup/sample/hellotodo/TodoWorkflow.kt
  kotlin/samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloWorkflow.kt
  kotlin/samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloWorkflowFragment.kt
  kotlin/samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloWorkflow.kt
  kotlin/samples/recyclerview/src/main/java/com/squareup/sample/recyclerview/AppWorkflow.kt
  kotlin/samples/recyclerview/src/main/java/com/squareup/sample/recyclerview/editablelistworkflow/EditableListWorkflow.kt
  kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/authworkflow/AuthWorkflow.kt
  kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/RunGameWorkflow.kt
  kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/TakeTurnsWorkflow.kt
  kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/mainworkflow/MainWorkflow.kt
  kotlin/samples/tictactoe/common/src/test/java/com/squareup/sample/mainworkflow/MainWorkflowTest.kt
  kotlin/samples/todo-android/common/src/main/java/com/squareup/sample/todo/TodoEditorWorkflow.kt
  kotlin/samples/todo-android/common/src/main/java/com/squareup/sample/todo/TodoListsAppWorkflow.kt
  kotlin/samples/todo-android/common/src/main/java/com/squareup/sample/todo/TodoListsWorkflow.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/StatefulWorkflow.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/StatelessWorkflow.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/Workflow.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/WorkflowAction.kt
  kotlin/workflow-runtime/src/jmh/java/com/squareup/workflow/WorkflowNodeBenchmark.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Behavior.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowId.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealRenderContextTest.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/SubtreeManagerTest.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowDiagnosticListenerIntegrationTest.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt
  kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/PublisherWorkerTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/TreeWorkflow.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerStressTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkflowCompositionIntegrationTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
  kotlin/workflow-tracing/src/test/java/com/squareup/workflow/diagnostic/tracing/TracingDiagnosticListenerTest.kt
  kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/WorkflowRunnerViewModelTest.kt
Labels: enhancement

#825 Upgrade coroutines to 1.3.3
  kotlin/build.gradle
  kotlin/legacy/legacy-workflow-rx2/src/test/java/com/squareup/workflow/legacy/rx2/CoroutineEventChannelTest.kt
  kotlin/samples/dungeon/timemachine-shakeable/src/main/java/com/squareup/sample/timemachine/shakeable/ShakeWorker.kt
  kotlin/trace-encoder/src/main/java/com/squareup/tracing/TraceEncoder.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowLoop.kt
  kotlin/workflow-rx2/src/main/java/com/squareup/workflow/rx2/PublisherWorker.kt
  kotlin/workflow-rx2/src/main/java/com/squareup/workflow/rx2/RxWorkers.kt
  kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/PublisherWorkerTest.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunnerViewModel.kt
Labels: dependencies

#828 Improve renderTester API
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RenderTester.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
Labels: enhancement

#800 Optimize re-rendering child workflows.
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Behavior.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/InlineLinkedList.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/SubtreeManager.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowChildNode.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/InlineLinkedListTest.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealRenderContextTest.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/SubtreeManagerTest.kt
Labels: enhancement

#832 Convert ViewRegistry to an interface.
  kotlin/samples/containers/app-poetry/src/main/java/com/squareup/sample/poetryapp/PoetryActivity.kt
  kotlin/samples/containers/app-raven/src/main/java/com/squareup/sample/ravenapp/RavenActivity.kt
  kotlin/samples/tictactoe/app/src/main/java/com/squareup/sample/mainactivity/MainActivity.kt
  kotlin/workflow-ui-android/build.gradle
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/BindingViewRegistry.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/CompositeViewRegistry.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/NamedBinding.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ViewRegistry.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowLayout.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/backstack/BackStackContainer.kt
  kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/BindingViewRegistryTest.kt
  kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/CompositeViewRegistryTest.kt
  kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/TestBinding.kt
Labels: enhancement

#835 Make RenderContext itself a Sink.
  kotlin/samples/containers/poetry/src/main/java/com/squareup/sample/poetry/PoemWorkflow.kt
  kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/DungeonAppWorkflow.kt
  kotlin/samples/dungeon/common/src/main/java/com/squareup/sample/dungeon/PlayerWorkflow.kt
  kotlin/samples/dungeon/timemachine-shakeable/src/main/java/com/squareup/sample/timemachine/shakeable/ShakeableTimeMachineWorkflow.kt
  kotlin/samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloWorkflow.kt
  kotlin/samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloWorkflow.kt
  kotlin/samples/recyclerview/src/main/java/com/squareup/sample/recyclerview/AppWorkflow.kt
  kotlin/samples/recyclerview/src/main/java/com/squareup/sample/recyclerview/editablelistworkflow/EditableListWorkflow.kt
  kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/authworkflow/AuthWorkflow.kt
  kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/RunGameWorkflow.kt
  kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/TakeTurnsWorkflow.kt
  kotlin/samples/todo-android/common/src/main/java/com/squareup/sample/todo/TodoEditorWorkflow.kt
  kotlin/samples/todo-android/common/src/main/java/com/squareup/sample/todo/TodoListsAppWorkflow.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/Sink.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/StatefulWorkflow.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/diagnostic/WorkflowUpdateDebugInfo.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealRenderContextTest.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RealRenderTester.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/TreeWorkflow.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkflowCompositionIntegrationTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
Labels: enhancement

#810 0.22 Changelog.
  CHANGELOG.md
Labels: blocked

#837 Make WorkflowAction covariant on OutputT again.
  kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/Sink.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/StatefulWorkflow.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/StatelessWorkflow.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/Workflow.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/WorkflowAction.kt
Labels: bug

#839 Undo making RenderContext a sink, give it a sink property instead.
  kotlin/samples/containers/poetry/src/main/java/com/squareup/sample/poetry/PoemWorkflow.kt
  kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/DungeonAppWorkflow.kt
  kotlin/samples/dungeon/common/src/main/java/com/squareup/sample/dungeon/PlayerWorkflow.kt
  kotlin/samples/dungeon/timemachine-shakeable/src/main/java/com/squareup/sample/timemachine/shakeable/ShakeableTimeMachineWorkflow.kt
  kotlin/samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloWorkflow.kt
  kotlin/samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloWorkflow.kt
  kotlin/samples/recyclerview/src/main/java/com/squareup/sample/recyclerview/AppWorkflow.kt
  kotlin/samples/recyclerview/src/main/java/com/squareup/sample/recyclerview/editablelistworkflow/EditableListWorkflow.kt
  kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/authworkflow/AuthWorkflow.kt
  kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/RunGameWorkflow.kt
  kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/TakeTurnsWorkflow.kt
  kotlin/samples/todo-android/common/src/main/java/com/squareup/sample/todo/TodoEditorWorkflow.kt
  kotlin/samples/todo-android/common/src/main/java/com/squareup/sample/todo/TodoListsAppWorkflow.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealRenderContextTest.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RealRenderTester.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/TreeWorkflow.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkflowCompositionIntegrationTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
Labels: enhancement

#841 Fix docs made incorrect by d34372bd.
  kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/Sink.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/StatefulWorkflow.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/diagnostic/WorkflowUpdateDebugInfo.kt
Labels: bug, documentation

#844 #842: Detect possible Worker mock setup issues.
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Workers.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/NullFlowWorker.java
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkersTest.kt
Labels: enhancement

#850 Give worker coroutines descriptive names for debugging.
  kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Workers.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkersTest.kt
Labels: enhancement
