Repository square/workflow, pull requests merged in 2019-07, with the labels that each got.

#426 Replace updates channel with rendering/snapshot and output Flows on WorkflowHost
  kotlin/build.gradle
  kotlin/samples/hello-terminal/terminal-workflow/src/main/java/com/squareup/sample/helloterminal/terminalworkflow/TerminalWorkflowRunner.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/RealWorkflowHost.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/WorkflowHost.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealWorkflowHostTest.kt
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkflowTester.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/WorkflowTesterTest.kt
  kotlin/workflow-ui-android/build.gradle
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunner.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunnerViewModel.kt
  kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/WorkflowRunnerViewModelTest.kt
Labels: enhancement

#446 Fix Worker backpressure (too much buffering).
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Workers.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkersTest.kt
Labels: bug

#449 Migrate from AssertJ to Truth, upgrade to Truth 1.0.
  kotlin/build.gradle
  kotlin/legacy/legacy-workflow-rx2/build.gradle
  kotlin/legacy/legacy-workflow-rx2/src/test/java/com/squareup/workflow/legacy/rx2/CoroutineEventChannelTest.kt
  kotlin/legacy/legacy-workflow-rx2/src/test/java/com/squareup/workflow/legacy/rx2/ReactorAsWorkflowIntegrationTest.kt
  kotlin/legacy/legacy-workflow-rx2/src/test/java/com/squareup/workflow/legacy/rx2/Rx2ReactorIntegrationTest.kt
  kotlin/legacy/legacy-workflow-rx2/src/test/java/com/squareup/workflow/legacy/rx2/Rx2WorkflowPoolIntegrationTest.kt
  kotlin/legacy/legacy-workflow-rx2/src/test/java/com/squareup/workflow/legacy/rx2/UncaughtExceptionsTest.kt
  kotlin/legacy/legacy-workflow-rx2/src/test/java/com/squareup/workflow/legacy/rx2/WorkerIntegrationTest.kt
  kotlin/legacy/legacy-workflow-rx2/src/test/java/com/squareup/workflow/legacy/rx2/WorkflowOperatorsTest.kt
  kotlin/samples/tictactoe/android/build.gradle
  kotlin/samples/tictactoe/common/build.gradle
  kotlin/samples/tictactoe/common/src/test/java/com/squareup/sample/gameworkflow/PlayerInfoTest.kt
  kotlin/samples/tictactoe/common/src/test/java/com/squareup/sample/gameworkflow/TakeTurnsWorkflowTest.kt
  kotlin/samples/tictactoe/common/src/test/java/com/squareup/sample/mainworkflow/MainWorkflowTest.kt
  kotlin/samples/todo-android/todo-android-app/build.gradle
  kotlin/samples/todo-android/todo-android-common/build.gradle
  kotlin/workflow-ui-core/build.gradle
  kotlin/workflow-ui-core/src/test/java/com/squareup/workflow/ui/CompatibleTest.kt
  kotlin/workflow-ui-core/src/test/java/com/squareup/workflow/ui/NamedTest.kt
Labels: enhancement

#451 Bump Kotlin to latest version (1.3.41), along with Dokka and detekt.
  kotlin/build.gradle
  kotlin/legacy/legacy-workflow-core/src/test/java/com/squareup/workflow/legacy/CoroutineWorkflowTest.kt
Labels: enhancement

#447 Replace WorkflowHost with the launchWorkflowIn function.
  kotlin/samples/hello-terminal/terminal-workflow/src/main/java/com/squareup/sample/helloterminal/terminalworkflow/TerminalWorkflowRunner.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/LaunchWorkflow.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/RealWorkflowHost.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/RenderingAndSnapshot.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/WorkflowHost.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Throwables.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Workers.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowLoop.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/LaunchWorkflowTest.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealWorkflowHostTest.kt
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkflowTester.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunnerViewModel.kt
  kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/WorkflowRunnerViewModelTest.kt
Labels: enhancement

#456 Don't throw from runningWorker when the worker finishes.
  kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt
Labels: bug

#465 Ensure the outer workflow runtime scope gets cancelled when the workflow loop cancels itself.
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/LaunchWorkflow.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/LaunchWorkflowTest.kt
Labels: bug

#441 Added builder functions for creating stateful workflows.
  kotlin/workflow-core/src/main/java/com/squareup/workflow/StatefulWorkflow.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/StatelessWorkflow.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/SnapshottingIntegrationTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkflowCompositionIntegrationTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RenderTesterTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/WorkflowTesterTest.kt
Labels: proposal

#484 Upgrade AGP to latest version (3.5.0-rc01).
  kotlin/build.gradle
Labels: enhancement

#483 Configure Travis to automatically deploy snapshots.
  .buildscript/deploy_snapshot.sh
  .travis.yml
Labels: enhancement

#481 Introduce mkdocs with deploy script.
  .gitignore
  .travis.yml
  README.md
  RELEASING.md
  deploy_website.sh
  docs/CHANGELOG.md
  docs/CONTRIBUTING.md
  docs/RELEASING.md
  docs/concepts.md
  docs/images/icon-square.png
  docs/index.md
  docs/overview.md
  docs/swift/building-a-view-controller-from-screen.md
  docs/swift/building-a-workflow.md
  mkdocs.yml
Labels: documentation, enhancement

#486 Fixed travis config for snapshot deployment
  .travis.yml
Labels: bug

#482 Configure deploy_website to publish kdocs.
  .gitignore
  deploy_website.sh
  kotlin/.buildscript/configure-dokka.gradle
  kotlin/build.gradle
  kotlin/workflow-core/build.gradle
  kotlin/workflow-runtime/build.gradle
  kotlin/workflow-rx2/build.gradle
  kotlin/workflow-testing/build.gradle
  kotlin/workflow-ui-android/build.gradle
  kotlin/workflow-ui-core/build.gradle
  mkdocs.yml
Labels: documentation, enhancement

#487 Fix dokka and push commands in deploy_website script.
  deploy_website.sh
Labels: bug

#493 Update docs to use a Square font.
  docs/css/app.css
  mkdocs.yml
Labels: documentation

#494 Publish Swift API docs as well, re-org the nav menu.
  .buildscript/build_swift_docs.sh
  deploy_website.sh
  mkdocs.yml
Labels: documentation

#495 Add analytics to docs site.
  deploy_website.sh
  mkdocs.yml
Labels: documentation

#498 Add analytics to swift API docs.
  .buildscript/build_swift_docs.sh
Labels: documentation

#496 [Swift] Allow reuse of sinks across render passes
  swift/Workflow/Sources/SubtreeManager.swift
  swift/Workflow/Sources/WorkflowHost.swift
  swift/Workflow/Tests/ConcurrencyTests.swift
  swift/Workflow/Tests/WorkflowHostTests.swift
Labels: enhancement

#500 Add linting for our documentation and fix existing errors.
  .markdownlint.rb
  .travis.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  RELEASING.md
  docs/concepts.md
  docs/faq.md
  docs/overview.md
  docs/swift/adding-workflow-to-a-project.md
  docs/swift/building-a-view-controller-from-screen.md
  docs/swift/building-a-workflow.md
  docs/swift/index.md
  docs/swift/tooling.md
  docs/swift/using-a-workflow-for-ui.md
  lint_docs.sh
Labels: documentation

#504 Document the new website deploy process and markdown linting.
  RELEASING.md
Labels: documentation

#505 Added social media links to website.
  mkdocs.yml
Labels: documentation

#509 Embed the Swift API docs in the regular site.
  .buildscript/build_swift_docs.sh
  .gitignore
  .travis.yml
  RELEASING.md
  deploy_website.sh
  lint_docs.sh
  mkdocs.yml
Labels: documentation

#513 Upgrade coroutines to latest version (1.3.0-RC).
  kotlin/build.gradle
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Workers.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowLoop.kt
Labels: enhancement

#510 Updated documentation structure, but no new content yet.
  docs/code-recipes.md
  docs/development-process.md
  docs/kotlin/index.md
  docs/tutorial/adding-workflow-to-a-project.md
  docs/tutorial/building-a-view-controller-from-screen.md
  docs/tutorial/building-a-workflow.md
  docs/tutorial/index.md
  docs/tutorial/tooling.md
  docs/tutorial/using-a-workflow-for-ui.md
  docs/userguide/comparison.md
  docs/userguide/concepts.md
  docs/userguide/core-patterns.md
  docs/userguide/core-worker.md
  docs/userguide/core-workflow.md
  docs/userguide/implementation.md
  docs/userguide/motivation.md
  docs/userguide/testing-concepts.md
  docs/userguide/ui-concepts.md
  mkdocs.yml
Labels: documentation
