Repository square/workflow, pull requests merged in 2019-11, with the labels that each got.

#717 Rename an old input parameter to props.
  kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt
Labels: bug

#687 Proposal: New render testing API for kotlin.
  kotlin/build.gradle
  kotlin/workflow-testing/build.gradle
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RealRenderTester.kt
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RenderTestResult.kt
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RenderTester.kt
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/TestRender.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/DeprecatedRenderTesterTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
Labels: proposal

#721 Inline dependency version numbers so Dependabot can update them.
  kotlin/build.gradle
Labels: dependencies

#746 Give Worker.doesSameWorkAs a default implementation that just compares by concrete type.
  kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt
  kotlin/workflow-core/src/test/java/com/squareup/workflow/WorkerTest.kt
Labels: enhancement

#747 Make `lifecycleOrNull` public.
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/Lifecycles.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ModalContainer.kt
Labels: enhancement

#691 Add ContainerView to enable SwiftUI integration
  swift/WorkflowUI/Sources/Container/WorkflowView.swift
Labels: enhancement

#756 Fix RenderTester not allowing output-less expectations to be specified after one with output.
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RealRenderTester.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
Labels: blocked

#755 Fix RenderTester not checking worker keys.
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RealRenderTester.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
Labels: bug

#761 Split the Android instrumentation tests into their own Travis shard.
  .travis.yml
Labels: enhancement

#770 BREAKING CHANGE: ViewRegistry is now a ContainerHint.
  kotlin/samples/containers/android/src/main/java/com/squareup/sample/container/masterdetail/MasterDetailContainer.kt
  kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/BoardView.kt
  kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/GameLayoutRunner.kt
  kotlin/samples/recyclerview/src/main/java/com/squareup/sample/recyclerview/BaseScreenLayoutRunner.kt
  kotlin/samples/recyclerview/src/main/java/com/squareup/sample/recyclerview/ChooseRowTypeViewBinding.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/AlertContainer.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/BuilderBinding.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ContainerHints.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/LayoutRunner.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ModalContainer.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ModalViewContainer.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ViewBinding.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ViewRegistry.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowLayout.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowViewStub.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/backstack/BackStackContainer.kt
  kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/ContainerHintsTest.kt
Labels: enhancement

#751 Update Cocoapods
  Gemfile
  Gemfile.lock
  swift/Samples/SampleApp/Podfile
  swift/Samples/TicTacToe/Podfile
  swift/Samples/Tutorial/Podfile
Labels: dependencies

#777 Fix some stuff in the RenderTester kdoc.
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RenderTester.kt
Labels: documentation

#754 Upgrade Kotlin and libraries to 1.3.60.
  kotlin/build.gradle
Labels: dependencies

#781 Bump moshi and moshi-kotlin from 1.9.1 to 1.9.2 in /kotlin
  kotlin/build.gradle
Labels: dependencies

#780 Upgrade ktlint to latest version.
  kotlin/build.gradle
  kotlin/samples/recyclerview/src/main/java/com/squareup/sample/recyclerview/inputrows/SwitchInputRow.kt
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkflowTester.kt
Labels: dependencies

#762 Upgrade Gradle to 6.0.1.
  kotlin/gradle/wrapper/gradle-wrapper.properties
Labels: dependencies
