Repository square/workflow, pull requests merged in 2019-10, with the labels that each got.

#630 Stop using onReceiveOrClosed because it is extremely broken.
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Workers.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkersTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerStressTest.kt
Labels: bug

#637 Change the return type of Worker.finished from T to Nothing.
  kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerTest.kt
Labels: enhancement

#617 Implement chrome trace file generation.
  kotlin/build.gradle
  kotlin/samples/dungeon/app/build.gradle
  kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/MainActivity.kt
  kotlin/samples/tictactoe/app/build.gradle
  kotlin/samples/tictactoe/app/src/main/java/com/squareup/sample/mainactivity/MainActivity.kt
  kotlin/samples/todo-android/app/build.gradle
  kotlin/samples/todo-android/app/src/main/java/com/squareup/sample/mainactivity/MainActivity.kt
  kotlin/settings.gradle
  kotlin/trace-encoder/README.md
  kotlin/trace-encoder/build.gradle
  kotlin/trace-encoder/gradle.properties
  kotlin/trace-encoder/src/main/java/com/squareup/tracing/ChromeTraceEvent.kt
  kotlin/trace-encoder/src/main/java/com/squareup/tracing/TraceEncoder.kt
  kotlin/trace-encoder/src/main/java/com/squareup/tracing/TraceEvent.kt
  kotlin/trace-encoder/src/main/java/com/squareup/tracing/TraceLogger.kt
  kotlin/trace-encoder/src/test/java/com/squareup/tracing/ChromeTraceEventTest.kt
  kotlin/trace-encoder/src/test/java/com/squareup/tracing/TraceEncoderTest.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/LaunchWorkflow.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/diagnostic/ChainedDiagnosticListener.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/diagnostic/SimpleLoggingDiagnosticListener.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/diagnostic/WorkflowDiagnosticListener.kt
  kotlin/workflow-tracing/README.md
  kotlin/workflow-tracing/build.gradle
  kotlin/workflow-tracing/gradle.properties
  kotlin/workflow-tracing/src/main/java/com/squareup/workflow/diagnostic/tracing/GcDetector.kt
  kotlin/workflow-tracing/src/main/java/com/squareup/workflow/diagnostic/tracing/MemoryStats.kt
  kotlin/workflow-tracing/src/main/java/com/squareup/workflow/diagnostic/tracing/TracingDiagnosticListener.kt
  kotlin/workflow-tracing/src/test/java/com/squareup/workflow/diagnostic/tracing/TracingDiagnosticListenerTest.kt
  kotlin/workflow-tracing/src/test/resources/com/squareup/workflow/diagnostic/tracing/expected_trace_file.txt
Labels: enhancement

#638 Remove racy hack in WorkerTester.
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkerTester.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerTest.kt
Labels: bug

#642 Embed the Droidcon NYC '19 video in the README.
  README.md
Labels: documentation

#643 Fix lint failure on README broken by #642.
  README.md
Labels: bug, documentation

#647 Add a section to RELEASING.md about publishing snapshot artifacts.
  RELEASING.md
Labels: documentation, enhancement

#650 Add an RxWorker class so Workers can be implemented without using experimental Flow APIs.
  kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt
  kotlin/workflow-rx2/src/main/java/com/squareup/workflow/rx2/RxWorker.kt
  kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/RxWorkerTest.kt
Labels: enhancement, proposal

#654 Make RxWorker and Flowable.asWorker use Publisher instead of Flowable.
  kotlin/workflow-rx2/src/main/java/com/squareup/workflow/rx2/PublisherWorker.kt
  kotlin/workflow-rx2/src/main/java/com/squareup/workflow/rx2/RxWorkers.kt
  kotlin/workflow-rx2/src/test/java/com/squareup/workflow/rx2/PublisherWorkerTest.kt
Labels: enhancement

#659 Link to the maven plugin issue about Gradle warning.
  kotlin/build.gradle
Labels: documentation

#663 Update tutorials for Swift 5/ReactiveSwift 6.0
  .travis.yml
  swift/Samples/Tutorial/Frameworks/Tutorial1Complete/Sources/Welcome/WelcomeWorkflow.swift
  swift/Samples/Tutorial/Frameworks/Tutorial2Complete/Sources/RootWorkflow.swift
  swift/Samples/Tutorial/Frameworks/Tutorial2Complete/Sources/Todo/List/TodoListWorkflow.swift
  swift/Samples/Tutorial/Frameworks/Tutorial2Complete/Sources/Welcome/WelcomeWorkflow.swift
  swift/Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/RootWorkflow.swift
  swift/Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/Todo/Edit/TodoEditWorkflow.swift
  swift/Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/Todo/List/TodoListWorkflow.swift
  swift/Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/Welcome/WelcomeWorkflow.swift
  swift/Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/RootWorkflow.swift
  swift/Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/Todo/Edit/TodoEditWorkflow.swift
  swift/Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/Todo/List/TodoListWorkflow.swift
  swift/Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/Todo/TodoWorkflow.swift
  swift/Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/Welcome/WelcomeWorkflow.swift
  swift/Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/RootWorkflow.swift
  swift/Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/Todo/Edit/TodoEditWorkflow.swift
  swift/Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/Todo/List/TodoListWorkflow.swift
  swift/Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/Todo/TodoWorkflow.swift
  swift/Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/Welcome/WelcomeWorkflow.swift
  swift/Samples/Tutorial/Tutorial3.md
  swift/Samples/Tutorial/Tutorial4.md
Labels: bug

#665 Fix the TracingDiagnosticListenerTest.golden value test.
  kotlin/workflow-tracing/build.gradle
  kotlin/workflow-tracing/src/main/java/com/squareup/workflow/diagnostic/tracing/GcDetector.kt
  kotlin/workflow-tracing/src/main/java/com/squareup/workflow/diagnostic/tracing/TracingDiagnosticListener.kt
  kotlin/workflow-tracing/src/test/java/com/squareup/workflow/diagnostic/tracing/TracingDiagnosticListenerTest.kt
  kotlin/workflow-tracing/src/test/resources/com/squareup/workflow/diagnostic/tracing/expected_trace_file.txt
Labels: bug

#672 Fix testRender kdoc to not say child workflows must be MockChildWorkflows.
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RenderTester.kt
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/TestOnlyRenderContext.kt
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/TestRender.kt
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/TestRenderResult.kt
Labels: documentation

#673 Make onEvent, makeActionSink, and makeEventSink include what action was lost to when they receive more than one event.
  kotlin/workflow-core/src/main/java/com/squareup/workflow/RenderContext.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealRenderContextTest.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt
Labels: enhancement, testing

#677 Remove robolectric dependency definition, we're never actually using it.
  kotlin/build.gradle
Labels: dependencies

#680 Eliminates a bunch of stale UseExperiment annotations.
  kotlin/workflow-core/src/main/java/com/squareup/workflow/LifecycleWorker.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/LaunchWorkflow.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/WorkflowSession.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/SubtreeManager.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowLoop.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/LaunchWorkflowTest.kt
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/MockWorker.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/FlowWorkersTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/WorkerSinkTest.kt
  kotlin/workflow-tracing/src/main/java/com/squareup/workflow/diagnostic/tracing/GcDetector.kt
Labels: merge when green

#682 Add configuration for merge-when-green app.
  .github/merge-when-green.yml
Labels: merge when green

#678 Make testing infra run double render passes to suss out side effect code in render methods.
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/LaunchWorkflow.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowLoop.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/testing/LaunchWorkflow.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/testing/WorkflowTestParams.kt
  kotlin/workflow-testing/build.gradle
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/TestRender.kt
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkflowTester.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/SnapshottingIntegrationTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RenderTesterTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/WorkflowTesterTest.kt
Labels: enhancement, merge when green, testing

#685 Fix red master after the merge-when-green bot incorrectly merged a PR before any CI had finished.
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/testing/LaunchWorkflow.kt
Labels: bug

#681 Make it possible to pass just the snapshot for the root workflow into the test methods.
  kotlin/workflow-core/src/main/java/com/squareup/workflow/Snapshot.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/SubtreeManager.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/TreeSnapshots.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/testing/LaunchWorkflow.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/testing/WorkflowTestParams.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/SubtreeManagerTest.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/TreeSnapshotsTest.kt
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/WorkflowTester.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/SnapshottingIntegrationTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/WorkflowTesterTest.kt
Labels: testing

#656 Add contact info to README.
  README.md
Labels: documentation, enhancement

#698 Update gradle to 5.6.3.
  kotlin/gradle/wrapper/gradle-wrapper.properties
  kotlin/gradlew
  kotlin/gradlew.bat
Labels: dependencies

#705 Add missing TraceLogger kdoc.
  kotlin/trace-encoder/src/main/java/com/squareup/tracing/TraceLogger.kt
Labels: bug, documentation

#707 Update info in RELEASING.md.
  RELEASING.md
Labels: bug, documentation

#708 Publish internal testing artifact, required by other published artifacts.
  kotlin/internal-testing-utils/build.gradle
  kotlin/internal-testing-utils/gradle.properties
Labels: bug

#709 Update changelog for v0.21.1.
  CHANGELOG.md
Labels: documentation

#710 Add note in RELEASING about only using Xcode 10.
  RELEASING.md
Labels: documentation
