Repository square/workflow, pull requests merged in 2019-08, with the labels that each got.

#514 Fixed typo in Swift Workflow docs.
  swift/Workflow/Sources/Workflow.swift
Labels: bug, documentation

#533 Create a Worker.transform operator.
  kotlin/samples/dungeon/common/src/main/java/com/squareup/sample/dungeon/AiWorkflow.kt
  kotlin/samples/dungeon/common/src/main/java/com/squareup/sample/dungeon/GameWorkflow.kt
  kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerTest.kt
Labels: enhancement

#551 Remove all direct dependencies on Kotlin Reflect.
  kotlin/build.gradle
  kotlin/legacy/legacy-workflow-core/build.gradle
  kotlin/legacy/legacy-workflow-core/src/main/java/com/squareup/workflow/legacy/Reactor.kt
  kotlin/legacy/legacy-workflow-rx2/build.gradle
  kotlin/legacy/legacy-workflow-rx2/src/main/java/com/squareup/workflow/legacy/rx2/Reactor.kt
  kotlin/samples/dungeon/app/build.gradle
  kotlin/samples/dungeon/common/build.gradle
  kotlin/samples/tictactoe/app/build.gradle
  kotlin/samples/tictactoe/common/build.gradle
  kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/gameworkflow/RunGameState.kt
  kotlin/samples/tictactoe/common/src/main/java/com/squareup/sample/mainworkflow/MainState.kt
  kotlin/samples/todo-android/app/build.gradle
  kotlin/samples/todo-android/common/build.gradle
  kotlin/workflow-core/build.gradle
  kotlin/workflow-runtime/build.gradle
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowId.kt
  kotlin/workflow-rx2/build.gradle
  kotlin/workflow-testing/build.gradle
  kotlin/workflow-ui-android/build.gradle
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/HandlesBack.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ViewRegistry.kt
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/WorkflowRunnerViewModel.kt
  kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/WorkflowRunnerViewModelTest.kt
  kotlin/workflow-ui-core/build.gradle
  kotlin/workflow-ui-core/src/main/java/com/squareup/workflow/ui/Named.kt
Labels: enhancement

#559 Add link to template repo to README.
  README.md
Labels: documentation

#582 Cleaned up dungeon actions.
  kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/DungeonAppWorkflow.kt
  kotlin/samples/dungeon/common/src/main/java/com/squareup/sample/dungeon/PlayerWorkflow.kt
Labels: documentation, enhancement
