Repository square/workflow, pull requests merged in 2020-01, with the labels that each got.

#846 Introduces BackButtonScreen to sample containers.
  kotlin/samples/containers/android/src/main/java/com/squareup/sample/container/BackButtonScreen.kt
  kotlin/samples/containers/android/src/main/java/com/squareup/sample/container/SampleContainers.kt
  kotlin/samples/containers/hello-back-button/build.gradle
  kotlin/samples/containers/hello-back-button/src/androidTest/java/com/squareup/sample/hellobackbutton/HelloBackButtonEspressoTest.kt
  kotlin/samples/containers/hello-back-button/src/main/AndroidManifest.xml
  kotlin/samples/containers/hello-back-button/src/main/java/com/squareup/sample/hellobackbutton/AreYouSureWorkflow.kt
  kotlin/samples/containers/hello-back-button/src/main/java/com/squareup/sample/hellobackbutton/HelloBackButtonActivity.kt
  kotlin/samples/containers/hello-back-button/src/main/java/com/squareup/sample/hellobackbutton/HelloBackButtonLayoutRunner.kt
  kotlin/samples/containers/hello-back-button/src/main/java/com/squareup/sample/hellobackbutton/HelloBackButtonWorkflow.kt
  kotlin/samples/containers/hello-back-button/src/main/res/layout/hello_back_button_layout.xml
  kotlin/samples/containers/hello-back-button/src/main/res/values/strings.xml
  kotlin/samples/containers/hello-back-button/src/main/res/values/styles.xml
  kotlin/samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloWorkflow.kt
  kotlin/samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloWorkflow.kt
  kotlin/samples/tictactoe/app/src/androidTest/java/com/squareup/sample/TicTacToeEspressoTest.kt
  kotlin/settings.gradle
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/NamedBinding.kt
Labels: enhancement

#863 Optimize re-rendering workers.
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/ActiveStagingList.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Behavior.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/LifetimeTracker.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/RealRenderContext.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/SubtreeManager.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkerChildNode.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowChildNode.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/ActiveStagingListTest.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/LifetimeTrackerTest.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/RealRenderContextTest.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowDiagnosticListenerIntegrationTest.kt
  kotlin/workflow-tracing/src/test/resources/com/squareup/workflow/diagnostic/tracing/expected_trace_file.txt
Labels: enhancement

#851 Make all workers run on the Unconfined dispatcher.
  kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Workers.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkersTest.kt
Labels: enhancement

#870 Add an empty ViewRegistry factory function.
  kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/ViewRegistry.kt
  kotlin/workflow-ui-android/src/test/java/com/squareup/workflow/ui/BindingViewRegistryTest.kt
Labels: enhancement

#872 Flag out WorkflowTesting APIs when in Release mode
  swift/WorkflowTesting/Sources/WorkflowActionTester.swift
  swift/WorkflowTesting/Sources/WorkflowRenderTester.swift
Labels: bug

#880 Fix racy broken WorkerStressTests.
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerStressTest.kt
Labels: bug

#881 Allow empty snapshots to be passed into launchWorkflowIn.
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/LaunchWorkflow.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowLoop.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/SnapshottingIntegrationTest.kt
Labels: enhancement

#884 Paramaterize the return type of Worker.finished() to make it more convenient to use in tests.
  kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
Labels: enhancement, testing

#889 Upgrade Dokka to 0.10.0 and maven publish to 0.9.0-SNAPSHOT.
  kotlin/.buildscript/configure-dokka.gradle
  kotlin/build.gradle
  kotlin/workflow-ui-android/build.gradle
Labels: bug

#906 Added explicit AndroidX dependencies
  kotlin/build.gradle
  kotlin/workflow-ui-android/build.gradle
Labels: dependencies

#908 Use KType instead of KClass in TypedWorker.
  kotlin/workflow-core/src/main/java/com/squareup/workflow/Worker.kt
  kotlin/workflow-core/src/test/java/com/squareup/workflow/WorkerTest.kt
  kotlin/workflow-tracing/src/test/resources/com/squareup/workflow/diagnostic/tracing/expected_trace_file.txt
Labels: enhancement

#909 Make verifyAction and verifyActionResult support no processed action.
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RealRenderTester.kt
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RenderTestResult.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
Labels: enhancement, testing

#914 Upgrade Gradle to 6.1.1.
  kotlin/gradle/wrapper/gradle-wrapper.jar
  kotlin/gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#916 Pass acceptOutput function to WorkflowNode constructor instead of every tick pass.
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/SubtreeManager.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowLoop.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/SubtreeManagerTest.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkflowNodeTest.kt
Labels: enhancement

#922 Upgrade Kotlin to 1.3.61.
  kotlin/build.gradle
Labels: dependencies

#924 Replaced activity-ktx dependency with activity.
  kotlin/build.gradle
Labels: dependencies
