Repository square/workflow, pull requests merged in 2020-02, with the labels that each got.

#935 Fix the module path for the recycler sample.
  kotlin/settings.gradle
Labels: bug

#939 Update README to document new Android UI artifacts.
  README.md
Labels: documentation

#940 Make the context used to start workers configurable for tests.
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/LaunchWorkflow.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/Workers.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowLoop.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/testing/LaunchWorkflow.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/testing/WorkflowTestParams.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/LaunchWorkflowTest.kt
  kotlin/workflow-runtime/src/test/java/com/squareup/workflow/internal/WorkersTest.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt
Labels: bug

#944 Make ViewRegistry's key set strictly-typed to KClass<*> instead of Any.
  kotlin/workflow-ui/core-android/src/main/java/com/squareup/workflow/ui/BindingViewRegistry.kt
  kotlin/workflow-ui/core-android/src/main/java/com/squareup/workflow/ui/CompositeViewRegistry.kt
  kotlin/workflow-ui/core-android/src/main/java/com/squareup/workflow/ui/ViewRegistry.kt
  kotlin/workflow-ui/core-android/src/test/java/com/squareup/workflow/ui/CompositeViewRegistryTest.kt
Labels: enhancement

#925 [swift] Add SplitScreenContainer Sample
  .gitignore
  .travis.yml
  swift/Samples/SplitScreenContainer/DemoApp/AppDelegate.swift
  swift/Samples/SplitScreenContainer/DemoApp/BarScreen.swift
  swift/Samples/SplitScreenContainer/DemoApp/DemoWorkflow.swift
  swift/Samples/SplitScreenContainer/DemoApp/FooScreen.swift
  swift/Samples/SplitScreenContainer/README.md
  swift/Samples/SplitScreenContainer/SnapshotTests/ReferenceImages_64/SplitScreenContainer_Unit_SnapshotTests.SplitScreenContainerScreenSnapshotTests/test_splitRatio_custom@2x.png
  swift/Samples/SplitScreenContainer/SnapshotTests/ReferenceImages_64/SplitScreenContainer_Unit_SnapshotTests.SplitScreenContainerScreenSnapshotTests/test_splitRatio_half@2x.png
  swift/Samples/SplitScreenContainer/SnapshotTests/ReferenceImages_64/SplitScreenContainer_Unit_SnapshotTests.SplitScreenContainerScreenSnapshotTests/test_splitRatio_quarter@2x.png
  swift/Samples/SplitScreenContainer/SnapshotTests/ReferenceImages_64/SplitScreenContainer_Unit_SnapshotTests.SplitScreenContainerScreenSnapshotTests/test_splitRatio_third@2x.png
  swift/Samples/SplitScreenContainer/SnapshotTests/SplitScreenContainerScreenSnapshotTests.swift
  swift/Samples/SplitScreenContainer/Sources/ContainerView.swift
  swift/Samples/SplitScreenContainer/Sources/SplitScreenContainerScreen.swift
  swift/Samples/SplitScreenContainer/Sources/SplitScreenContainerViewController.swift
  swift/Samples/SplitScreenContainer/SplitScreenContainer.podspec
Labels: enhancement

#949 Update ktlint gradle plugin to 9.2.0.
  kotlin/build.gradle
Labels: dependencies

#950 Plumb workerContext to child workflows.
  CHANGELOG.md
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/SubtreeManager.kt
  kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerCompositionIntegrationTest.kt
Labels: bug

#952 Bump python version for static site shard on release branch
  .travis.yml
Labels: documentation

#969 Fix type parameter for expectWorker accepting Worker instance.
  CHANGELOG.md
  kotlin/workflow-testing/src/main/java/com/squareup/workflow/testing/RenderTester.kt
  kotlin/workflow-testing/src/test/java/com/squareup/workflow/testing/RealRenderTesterTest.kt
Labels: bug, testing

#703 Basic Jetpack Compose UI integration with sample.
  kotlin/.buildscript/configure-compose.gradle
  kotlin/build.gradle
  kotlin/samples/hello-compose-binding/build.gradle
  kotlin/samples/hello-compose-binding/src/androidTest/java/com/squareup/sample/hellocomposebinding/HelloBindingTest.kt
  kotlin/samples/hello-compose-binding/src/main/AndroidManifest.xml
  kotlin/samples/hello-compose-binding/src/main/java/com/squareup/sample/hellocomposebinding/HelloBinding.kt
  kotlin/samples/hello-compose-binding/src/main/java/com/squareup/sample/hellocomposebinding/HelloBindingActivity.kt
  kotlin/samples/hello-compose-binding/src/main/java/com/squareup/sample/hellocomposebinding/HelloWorkflow.kt
  kotlin/samples/hello-compose-binding/src/main/res/values/strings.xml
  kotlin/samples/hello-compose-binding/src/main/res/values/styles.xml
  kotlin/settings.gradle
  kotlin/workflow-ui/core-compose/README.md
  kotlin/workflow-ui/core-compose/build.gradle
  kotlin/workflow-ui/core-compose/gradle.properties
  kotlin/workflow-ui/core-compose/src/main/AndroidManifest.xml
  kotlin/workflow-ui/core-compose/src/main/java/com/squareup/workflow/ui/compose/ComposeViewBinding.kt
Labels: enhancement, proposal

#983 Upgrade AGP to 4.0.0-beta01.
  kotlin/build.gradle
Labels: dependencies

#989 Update binary-compatibility-validator plugin to 0.2.1.
  kotlin/.buildscript/binary-validation.gradle
  kotlin/build.gradle
  kotlin/legacy/legacy-workflow-core/api/legacy-workflow-core.api
  kotlin/legacy/legacy-workflow-rx2/api/legacy-workflow-rx2.api
  kotlin/workflow-core/api/workflow-core.api
  kotlin/workflow-rx2/api/workflow-rx2.api
  kotlin/workflow-testing/api/workflow-testing.api
  kotlin/workflow-ui/backstack-android/api/backstack-android.api
  kotlin/workflow-ui/core-android/api/core-android.api
  kotlin/workflow-ui/core-compose/api/core-compose.api
  kotlin/workflow-ui/modal-android/api/modal-android.api
Labels: kotlin
